program CaimanERP;
//{$WEAKLINKRTTI ON}


uses
  Forms,
  UDM in 'UDM.pas' {DM: TDataModule},
  USenha in 'USenha.pas' {FrmSenha},
  Ubibli1 in 'Units\Ubibli1.pas',
  UCadNovo in 'UNITS\UCadNovo.pas' {FrmCadastroNovo},
  UCadConvenio in 'UCadConvenio.pas' {FrmCadConvenio},
  UCadLab in 'UCadLab.pas' {FrmCadLab},
  UConsNovo in 'UNITS\UConsNovo.pas' {FrmConsNovo},
  UConsLab in 'UConsLab.pas' {FrmConsLab},
  UConsConvenio in 'UConsConvenio.pas' {FrmConsConvenio},
  UCadClassifCliente in 'UCadClassifCliente.pas' {FrmCadClassifCliente},
  UConsClassifCliente in 'UConsClassifCliente.pas' {FrmConsClassifCliente},
  UCadCli in 'UCadCli.pas' {FrmCadCli},
  UConsCli in 'UConsCli.pas' {FrmConsCli},
  UCadEmp in 'UCadEmp.pas' {FrmCadEmp},
  UConsEmp in 'UConsEmp.pas' {FrmConsEmp},
  UCadFor in 'UCadFor.pas' {FrmCadFor},
  UConsFor in 'UConsFor.pas' {FrmConsFor},
  UCadBanco in 'UCadBanco.pas' {FrmCadBanco},
  UConsBanco in 'UConsBanco.pas' {FrmConsBanco},
  UCadConta in 'UCadConta.pas' {FrmCadConta},
  UConsConta in 'UConsConta.pas' {FrmConsConta},
  UCadCheque in 'UCadCheque.pas' {FrmCadCheque},
  UConsCheque in 'UConsCheque.pas' {FrmConsCheque},
  USelEmp in 'USelEmp.pas' {FrmSelEmp},
  UCadMotivo in 'UCadMotivo.pas' {FrmCadMotivo},
  UConsMotivo in 'UConsMotivo.pas' {FrmConsMotivo},
  UDeposito in 'UDeposito.pas' {FrmDeposito},
  UConsCheques in 'UConsCheques.pas' {FrmConsCheques},
  UCadGICMS in 'UCadGICMS.pas' {FrmCadGICMS},
  UConsGRP in 'UConsGRP.pas' {FrmConsGRP},
  UCadSecao in 'UCadSecao.pas' {FrmCadSecao},
  UConsSecao in 'UConsSecao.pas' {FrmConsSecao},
  UContasPagar in 'UContasPagar.pas' {FrmContasPagar},
  UConsLancPagar in 'UConsLancPagar.pas' {FrmConsLancPagar},
  UContasPagarPag in 'UContasPagarPag.pas' {FrmContasPagarPag},
  UPagamento in 'UPagamento.pas' {FrmPagamento},
  UCancelaPagto in 'UCancelaPagto.pas' {FrmCancelaPagto},
  UConsPagar in 'UConsPagar.pas' {FrmConsPagar},
  UCadTipoVenda in 'UCadTipoVenda.pas' {FrmCadTipoVenda},
  UConsTipoVenda in 'UConsTipoVenda.pas' {FrmConsTipoVenda},
  UContasReceber in 'UContasReceber.pas' {FrmLancContasReceber},
  UConsLancReceber in 'UConsLancReceber.pas' {FrmConsLancReceber},
  UCadCaixa in 'UCadCaixa.pas' {FrmCadCaixa},
  UConsCaixa in 'UConsCaixa.pas' {FrmConsCaixa},
  UConfiguracoes in 'UConfiguracoes.pas' {FrmConfiguracoes},
  UConsProd in 'UConsProd.pas' {FrmConsProd},
  UContasRecRec in 'UContasRecRec.pas' {FrmContasRecRec},
  UContasRecItens in 'UContasRecItens.pas' {FrmContasRecItens},
  URecebimento in 'URecebimento.pas' {FrmRecebimento},
  UParcelaPendente in 'UParcelaPendente.pas' {FrmParcelaPendente},
  UCancelaRecebimento in 'UCancelaRecebimento.pas' {FrmCancelaRecebimento},
  UConsContasRec in 'UConsContasRec.pas' {FrmConsContasRec},
  UEntradas in 'UEntradas.pas' {FrmEntradas},
  UConsEntrada in 'UConsEntrada.pas' {FrmConsEntrada},
  UAcertoEstoque in 'UAcertoEstoque.pas' {FrmAcertoEstoque},
  UConsAcertoEstoque in 'UConsAcertoEstoque.pas' {FrmConsAcertoEstoque},
  UConsEstoque in 'UConsEstoque.pas' {FrmConsEstoque},
  UVenda in 'UVenda.pas' {FrmVenda},
  UAlteraPreco in 'UAlteraPreco.pas' {FrmAlteraPreco},
  UAltPreco in 'UAltPreco.pas' {FrmAltPreco},
  UConsAniversario in 'UConsAniversario.pas' {FrmConsAniversario},
  UCadFunc in 'UCadFunc.pas' {FrmCadFunc},
  UConsFunc in 'UConsFunc.pas' {FrmConsFunc},
  UCadUsuario in 'UCadUsuario.pas' {FrmCadUsu},
  UConsUsu in 'UConsUsu.pas' {FrmConsUsu},
  UFRMRELATORIO in 'UNITS\UFRMRELATORIO.pas' {FrmRelatorio},
  URelEmp in 'URelEmp.pas' {FrmRelEmp},
  URelFor in 'URelFor.pas' {FrmRelFor},
  URelConvenio in 'URelConvenio.pas' {FrmRelConvenio},
  URelLab in 'URelLab.pas' {FrmRelLab},
  UFechaVenda in 'UFechaVenda.pas' {FrmFechaVenda},
  UAlteraParcela in 'UAlteraParcela.pas' {FrmAlteraParcela},
  UEtiqueta in 'UEtiqueta.pas' {FrmEtiqueta},
  UProdutoCliente in 'UProdutoCliente.pas' {FrmProdutoCliente},
  UVendasProduto in 'UVendasProduto.pas' {FrmVendasProduto},
  URelConv in 'URelConv.pas' {FrmRelConv},
  UConsVendaCaixa in 'UConsVendaCaixa.pas' {FrmConsVendaCaixa},
  URelGrupoICMS in 'URelGrupoICMS.pas' {FrmRelGrupoICMS},
  URelSecao in 'URelSecao.pas' {FrmRelSecao},
  URelClaCliente in 'URelClaCliente.pas' {FrmRelClaCliente},
  URelBanco in 'URelBanco.pas' {FrmRelBanco},
  URelContasCorrente in 'URelContasCorrente.pas' {FrmRelContasCorrente},
  URelMotivo in 'URelMotivo.pas' {FrmRelMotivo},
  URelFuncionario in 'URelFuncionario.pas' {FrmRelFuncionario},
  URelTipoVenda in 'URelTipoVenda.pas' {FrmRelTipoVenda},
  URecCliConv in 'URecCliConv.pas' {FrmRelCliConv},
  URelCTR in 'URelCTR.pas' {FrmRelCTR},
  URelContasPagar in 'URelContasPagar.pas' {FrmRelContasAPagar},
  URelInventario in 'URelInventario.pas' {FrmRelInventario},
  UQRelCadEmp in 'UQRelCadEmp.pas' {FrmQRelEmp},
  UQRelCadFor in 'UQRelCadFor.pas' {FrmQRelCadFor},
  UQRelCadConvenio in 'UQRelCadConvenio.pas' {FrmQRelConv},
  UQRelCadClassif in 'UQRelCadClassif.pas' {FrmQRelCadClassif},
  UQRelCadLab in 'UQRelCadLab.pas' {FrmQRelCadLab},
  UQRelCadGrp in 'UQRelCadGrp.pas' {FrmQRelGrp},
  UQRelSec in 'UQRelSec.pas' {FrmQRelSec},
  UQRelBanco in 'UQRelBanco.pas' {FrmQRelBanco},
  UQRelConta in 'UQRelConta.pas' {FrmQRelConta},
  UQRelMotivo in 'UQRelMotivo.pas' {FrmQRelMotivo},
  UQRelFunc in 'UQRelFunc.pas' {FrmQRelFunc},
  UQRelTipoVenda in 'UQRelTipoVenda.pas' {FrmQRelTPV},
  UQRelClienteGeral in 'UQRelClienteGeral.pas' {FrmQRelCliGeral},
  URelClienteGeral in 'URelClienteGeral.pas' {FrmRelClienteGeral},
  UQRelClienteConv in 'UQRelClienteConv.pas' {FrmQRelClienteConvenio},
  UQRelConvDet in 'UQRelConvDet.pas' {FrmQRelConvDetalhado},
  UQrelConvRes in 'UQrelConvRes.pas' {FrmQRelConvRes},
  UQRelAReceber in 'UQRelAReceber.pas' {FrmQRelAReceber},
  UQRelRecebidas in 'UQRelRecebidas.pas' {FrmQRelRecebidas},
  URelProduto in 'URelProduto.pas' {FrmRelProduto},
  UQRelProdutoGeral in 'UQRelProdutoGeral.pas' {FrmQRelProdutoGeral},
  URelProdLab in 'URelProdLab.pas' {FrmQRelProdLab},
  UQRelProdSecao in 'UQRelProdSecao.pas' {FrmQRelProdSecao},
  UQRelProdGRP in 'UQRelProdGRP.pas' {FrmQRelProdGRP},
  UConsEntradasProduto in 'UConsEntradasProduto.pas' {FrmConsEntradasProduto},
  UConsProdVenda in 'UConsProdVenda.pas' {FrmConsProdVenda},
  URelEntradas in 'URelEntradas.pas' {FrmRelEntradas},
  URelRecebimento in 'URelRecebimento.pas' {FrmRelRecebimento},
  URelExtratoCliente in 'URelExtratoCliente.pas' {FrmRelExtratoCliente},
  UQRelExtratoCliente in 'UQRelExtratoCliente.pas' {FrmQRelExtratoCliente},
  UQRelAPagarVenc in 'UQRelAPagarVenc.pas' {FrmQRelAPagarVenc},
  UQRelAPagarFor in 'UQRelAPagarFor.pas' {FrmQRelAPagarFor},
  UQRelPagasDtPagto in 'UQRelPagasDtPagto.pas' {FrmQRelPagasDtPagto},
  UQRelPagasFor in 'UQRelPagasFor.pas' {FrmQRelPagasFor},
  UCadGrupoUsuario in 'UCadGrupoUsuario.pas' {FrmCadGrupoUsuario},
  UConsGrupoUsuario in 'UConsGrupoUsuario.pas' {FrmConsGrupoUsuario},
  UAcesso in 'UAcesso.pas' {FrmAcesso},
  URelAbaixoMinimo in 'URelAbaixoMinimo.pas' {FrmRelAbaixoMinimo},
  UQRelEntradas in 'UQRelEntradas.pas' {FrmQRelEntradas},
  URelVendas in 'URelVendas.pas' {FrmRelVendas},
  UQRelVendas in 'UQRelVendas.pas' {FrmQRelVendas},
  URelProdutosVendidos in 'URelProdutosVendidos.pas' {FrmRelProdutosVendidos},
  UQRelProdutosVendidos in 'UQRelProdutosVendidos.pas' {FrmQRelProdutosVendidos},
  UCadSetor in 'UCadSetor.pas' {FrmCadSetor},
  UConsSetor in 'UConsSetor.pas' {FrmConsSetor},
  URelBal in 'URelBal.pas' {FrmRelBal},
  UQRelBal in 'UQRelBal.pas' {FrmQRelBal},
  UItensEntradas in 'UItensEntradas.pas' {FrmItensEntradas},
  URelClienteNeg in 'URelClienteNeg.pas' {FrmRelClienteNeg},
  UQRelNegRes in 'UQRelNegRes.pas' {FrmQRelNegRes},
  UQRelNegDet in 'UQRelNegDet.pas' {FrmQRelNegDet},
  ULancContasPagar in 'ULancContasPagar.pas' {FrmLancContasPagar},
  URelEstoque in 'URelEstoque.pas' {FrmRelEstoque},
  UQRelEstoque in 'UQRelEstoque.pas' {FrmQRelEstoque},
  UCadTipoES in 'UCadTipoES.pas' {FrmCadTipoES},
  UConsTipoES in 'UConsTipoES.pas' {FrmConsTipoES},
  UOutrasSaidas in 'UOutrasSaidas.pas' {FrmOutrasSaidas},
  UOutrasEntradas in 'UOutrasEntradas.pas' {FrmOutrasEntradas},
  UConsOutrasSaidas in 'UConsOutrasSaidas.pas' {FrmConsOutrasSaidas},
  UConsOutrasEntradas in 'UConsOutrasEntradas.pas' {FrmConsOutrasEntradas},
  URelOutrasSaidas in 'URelOutrasSaidas.pas' {FrmRelOutrasSaidas},
  UQRelOutrasSaidas in 'UQRelOutrasSaidas.pas' {FrmQRelOutrasSaidas},
  URelOutrasEntradas in 'URelOutrasEntradas.pas' {FrmRelOutrasEntradas},
  UQRelOutrasEntradas in 'UQRelOutrasEntradas.pas' {FrmQRelOutrasEntradas},
  UConsProdRapida in 'UConsProdRapida.pas' {FrmConsProdRapida},
  URelVendasLucro in 'URelVendasLucro.pas' {FrmRelVendasLucro},
  UQRelVendasLucro in 'UQRelVendasLucro.pas' {FrmQRelVendasLucro},
  URelCTRRes in 'URelCTRRes.pas' {FrmRelAReceberRes},
  UQRelCTRRes in 'UQRelCTRRes.pas' {FrmQRelCTRRes},
  ULancCheques in 'ULancCheques.pas' {FrmLancCheques},
  URecEstoque in 'URecEstoque.pas' {FrmRecEstoque},
  ULancCC in 'ULancCC.pas' {FrmLancCC},
  UCadTipoDoc in 'UCadTipoDoc.pas' {FrmCadTipoDoc},
  UConsTipoDoc in 'UConsTipoDoc.pas' {FrmConsTipoDoc},
  UConsCCChequesAberto in 'UConsCCChequesAberto.pas' {FrmConsCCChequesAberto},
  UExtratoCC in 'UExtratoCC.pas' {FrmExtratoCC},
  UConsSaldoCC in 'UConsSaldoCC.pas' {FrmSaldoCC},
  UConsLancCC in 'UConsLancCC.pas' {FrmConsLanCC},
  URelCCAberto in 'URelCCAberto.pas' {FrmRelCCAberto},
  UQRelCCAberto in 'UQRelCCAberto.pas' {FrmQRelCCAberto},
  URecConvenio in 'URecConvenio.pas' {FrmRecConvenio},
  UGeraBalanca in 'UGeraBalanca.pas' {FrmGeraBalanca},
  URelCusto in 'URelCusto.pas' {FrmRelCusto},
  UQRelCusto in 'UQRelCusto.pas' {FrmQRelCusto},
  URepasseCheque in 'URepasseCheque.pas' {FrmRepasseCheque},
  UQRelRepasseCheque in 'UQRelRepasseCheque.pas' {FrmQRelRepasseCheque},
  UConsRepasseCheque in 'UConsRepasseCheque.pas' {FrmConsRepasse},
  USobre in 'USobre.pas' {FrmSobre},
  URelChequeAberto in 'URelChequeAberto.pas' {FrmRelCheque},
  UQRelChequeAberto in 'UQRelChequeAberto.pas' {FrmQRelCheque},
  URelEntradasProduto in 'URelEntradasProduto.pas' {FrmRelEntradasProduto},
  UQRelEntradasProduto in 'UQRelEntradasProduto.pas' {FrmQRelEntradasProduto},
  URelVendasProduto in 'URelVendasProduto.pas' {FrmRelVendasProduto},
  UQRelVendasProduto in 'UQRelVendasProduto.pas' {FrmQRelVendasProduto},
  UQRelInvent in 'UQRelInvent.pas' {FrmQRelInvent},
  UCadTipoCobranca in 'UCadTipoCobranca.pas' {FrmCadTipoCobranca},
  UConsTipoCobranca in 'UConsTipoCobranca.pas' {FrmConsTipoCobranca},
  ULancContabil in 'ULancContabil.pas' {FrmLancContabil},
  UConsLancPadrao in 'UConsLancPadrao.pas' {FrmConsLancPadrao},
  UTrocaCobranca in 'UTrocaCobranca.pas' {FrmTrocaCobranca},
  URelEtiqueta in 'URelEtiqueta.pas' {FrmRelEtiqueta},
  UCadCFOP in 'UCadCFOP.pas' {FrmCadCFOP},
  UConsCFOP in 'UConsCFOP.pas' {FrmConsCFOP},
  URelExtratoFor in 'URelExtratoFor.pas' {FrmRelExtratoFor},
  UQRelExtratoFor in 'UQRelExtratoFor.pas' {FrmQRelExtratoFor},
  UCadTransp in 'UCadTransp.pas' {FrmCadTransp},
  UConsTransp in 'UConsTransp.pas' {FrmConsTransp},
  UConsNotaFiscal in 'UConsNotaFiscal.pas' {FrmConsNotaFiscal},
  URelExtratoCC in 'URelExtratoCC.pas' {FrmRelExtratoCC},
  UQRelExtratoCC in 'UQRelExtratoCC.pas' {FrmQRelExtratoCC},
  UCancNotaFiscal in 'UCancNotaFiscal.pas' {FrmCancNotaFiscal},
  URelProdGRP in 'URelProdGRP.pas' {FrmRelProdGRP},
  URelCTREmitidas in 'URelCTREmitidas.pas' {FrmRelCTREmitidas},
  UQRelCTREmissao in 'UQRelCTREmissao.pas' {FrmQRelCTREmitidas},
  UMapaResumo in 'UMapaResumo.pas' {FrmMapaResumo},
  URelMapaResumo in 'URelMapaResumo.pas' {FrmRelMapaResumo},
  URelResumoMapa in 'URelResumoMapa.pas' {FrmRelResumoMapa},
  UQRelResumoMapa in 'UQRelResumoMapa.pas' {FrmQRelResumoMapa},
  URelPisCofins in 'URelPisCofins.pas' {FrmRelPisCofins},
  UConsNFCFOP in 'UConsNFCFOP.pas' {FrmConsNFCFOP},
  UQRelNFCFOP in 'UQRelNFCFOP.pas' {FrmQRelNFCFOP},
  USitCli in 'USitCli.pas' {FrmSitCli},
  UCadAdmCartaoCredito in 'UCadAdmCartaoCredito.pas' {FrmCadAdmCartaoCredito},
  UConsAdmCartaoCredito in 'UConsAdmCartaoCredito.pas' {FrmConsAdmCartaoCredito},
  ULancCTRADM in 'ULancCTRADM.pas' {FrmLancCTRADM},
  URecAdm in 'URecAdm.pas' {FrmRECADM},
  UCtrAdmRec in 'UCtrAdmRec.pas' {FrmCtrAdmRec},
  UConsCTRAdm in 'UConsCTRAdm.pas' {FrmConsCTRAdm},
  UFichaCliente in 'UFichaCliente.pas' {FrmFichaCliente},
  UCadCarta in 'UCadCarta.pas' {FrmCadCarta},
  UConsCartas in 'UConsCartas.pas' {FrmConsCartas},
  UMalaDireta in 'UMalaDireta.pas' {FrmMalaDireta},
  UMalaSel in 'UMalaSel.pas' {FrmMalaSel},
  UQRelCarta in 'UQRelCarta.pas' {FrmQRelCarta},
  UConsCtrAdmCartaoCred in 'UConsCtrAdmCartaoCred.pas' {FrmConsAdmCartaoCred},
  UExtratoEstoque in 'UExtratoEstoque.pas' {FrmExtratoEstoque},
  UQRelAReceberVencto in 'UQRelAReceberVencto.pas' {FrmQRelAReceberVencto},
  UCTRDevolucao in 'UCTRDevolucao.pas' {FrmCTRDevolucao},
  URelResumoVendas in 'URelResumoVendas.pas' {FrmRelResumoVendas},
  UQRelResumoVendas in 'UQRelResumoVendas.pas' {FrmQRelResumoVendas},
  UBematech in 'Units\UBematech.pas',
  UDadosVenda in 'UDadosVenda.pas' {FrmDadosVenda},
  URelVendasSecao in 'URelVendasSecao.pas' {FrmRelVendasSecao},
  UQRelVendasSecao in 'UQRelVendasSecao.pas' {FrmQRelVendasSecao},
  UMarcarProd in 'UMarcarProd.pas' {FrmMarcarProd},
  UConsAcrescimos in 'UConsAcrescimos.pas' {FrmConsAcrescimos},
  UDesativarProdutos in 'UDesativarProdutos.pas' {FrmDesativarProdutos},
  URelProd in 'URelProd.pas' {FrmRelProd},
  UQRelProd in 'UQRelProd.pas' {FrmQRelProd},
  URelMargemLucro in 'URelMargemLucro.pas' {FrmRelMargemLucro},
  UQRelMargemLucro in 'UQRelMargemLucro.pas' {FrmQRelMargemLucro},
  UItensVenda in 'UItensVenda.pas' {FrmItensVenda},
  UExpImpProduto in 'UExpImpProduto.pas' {FrmExpImpProduto},
  UsenhaLiberarVenda in 'UsenhaLiberarVenda.pas' {FrmSenhaLiberaVenda},
  URelGiro in 'URelGiro.pas' {FrmRelGiro},
  UQRelGiro in 'UQRelGiro.pas' {FrmQRelGiro},
  URelPMV in 'URelPMV.pas' {FrmRelPMV},
  UQRelPMV in 'UQRelPMV.pas' {FrmQRelPMV},
  URelAMR in 'URelAMR.pas' {FrmRelAMR},
  UQRelAMR in 'UQRelAMR.pas' {FrmQRelAMR},
  UCTRDuplicata in 'UCTRDuplicata.pas' {FrmCTRDuplicata},
  URelEnvelope in 'URelEnvelope.pas' {FrmRelEnvelope},
  UQrelDespesaReceita in 'UQrelDespesaReceita.pas' {FrmQRelDespesaReceita},
  UQRelEstoqueMinimo in 'UQRelEstoqueMinimo.pas' {FrmQRelEstoqueMinimo},
  UQRelItensEntradas in 'UQRelItensEntradas.pas' {FrmQRelItensEntradas},
  UCadVales in 'UCadVales.pas' {FrmCadVales},
  UValesBaixa in 'UValesBaixa.pas' {FrmValesBaixa},
  UCancelaBaixaVale in 'UCancelaBaixaVale.pas' {FrmCancelaBaixaVale},
  UConsValesFuncionario in 'UConsValesFuncionario.pas' {FrmConsValesFuncionario},
  UCadPromocao in 'UCadPromocao.pas' {FrmCadPromocao},
  UAtualizaPromocao in 'UAtualizaPromocao.pas' {FrmAtualizaPromocao},
  URelPrecosPromocao in 'URelPrecosPromocao.pas' {FrmRelPrecoPromocao},
  ULiberaSistema in 'ULiberaSistema.pas' {FrmLiberaSistema},
  UQRelBebidas in 'UQRelBebidas.pas' {FrmQRelBebidas},
  UDaruma in 'Units\UDaruma.pas',
  UQRelAniverCliente in 'UQRelAniverCliente.pas' {FrmQRelAniverCliente},
  UQRelAniverFilho in 'UQRelAniverFilho.pas' {FrmQRelAniverFilho},
  Elgin in 'Units\Elgin.pas',
  UQRelRecebidasRes in 'UQRelRecebidasRes.pas' {FrmQRelRecebidasRes},
  UConsModelo in 'UConsModelo.pas' {FrmConsModelo},
  Sintegra in 'Units\Sintegra.pas',
  USintegra in 'USintegra.pas' {FrmSintegra},
  UGeraInventario in 'UGeraInventario.pas' {FrmGeraInventario},
  URegEntradas in 'URegEntradas.pas' {FrmRegEntradas},
  UConsRegEntradas in 'UConsRegEntradas.pas' {FrmConsRegEntradas},
  URegSaidas in 'URegSaidas.pas' {FrmRegSaidas},
  UConsRegSaidas in 'UConsRegSaidas.pas' {FrmConsRegSaidas},
  URelRegEntradas in 'URelRegEntradas.pas' {FrmRelRegEntradas},
  UQRelRegEntradas in 'UQRelRegEntradas.pas' {FrmQRelRegEntradas},
  URelRegSaidas in 'URelRegSaidas.pas' {FrmRelRegSaidas},
  UQRelRegSaidas in 'UQRelRegSaidas.pas' {FrmQRelRegSaidas},
  UUltimaCompra in 'UUltimaCompra.pas' {FrmUltimaCompra},
  UAlterarSecaoGrupo in 'UAlterarSecaoGrupo.pas' {FrmAlterarSecao},
  UQRelRegEntResumido in 'UQRelRegEntResumido.pas' {FrmQRelRegEntResumido},
  UQRelRegSaidasResumido in 'UQRelRegSaidasResumido.pas' {FrmQRelRegSaidasResumido},
  URelProdutosAlterados in 'URelProdutosAlterados.pas' {FrmRelProdutosAlterados},
  UQRelProdutosAlterados in 'UQRelProdutosAlterados.pas' {FrmQRelProdutosAlterados},
  UCadReceitas in 'UCadReceitas.pas' {FrmCadReceitas},
  UConsReceitas in 'UConsReceitas.pas' {FrmConsReceitas},
  UQRelRegEntResNota in 'UQRelRegEntResNota.pas' {FrmQRelRegEntResNota},
  UQRelMapaDetalhado in 'UQRelMapaDetalhado.pas' {FrmRelMapaDetalhado},
  URelMapaDetalhado in 'URelMapaDetalhado.pas' {FrmQRelMapaDetalhado},
  UProdutosComposicao in 'UProdutosComposicao.pas' {FrmProdutosComposicao},
  UQRelInventPrecoVenda in 'UQRelInventPrecoVenda.pas' {FrmQRelInventPrecoVenda},
  UQRelEstoquePrecoVenda in 'UQRelEstoquePrecoVenda.pas' {FrmQRelEstoquePrecoVenda},
  UCadTipoProduto in 'UCadTipoProduto.pas' {FrmCadTipoProduto},
  UConsTipoProduto in 'UConsTipoProduto.pas' {FrmConsTipoProduto},
  UQRelEstoqueCustoVenda in 'UQRelEstoqueCustoVenda.pas' {FrmQRelEstoqueCustoVenda},
  Extensos in 'Units\Extensos.pas',
  UQRelProdComposicao in 'UQRelProdComposicao.pas' {FrmQRelProdComposicao},
  UPrecosProgramados in 'UPrecosProgramados.pas' {FrmPrecosProgramados},
  UCadClassifContasPagar in 'UCadClassifContasPagar.pas' {FrmCadClassifContasPagar},
  UConsClassifContasPagar in 'UConsClassifContasPagar.pas' {FrmConsClassifContasPagar},
  UCadEmbalagem in 'UCadEmbalagem.pas' {FrmCadEmbalagem},
  UConsEmbalagens in 'UConsEmbalagens.pas' {FrmConsEmbalagens},
  URelNF in 'URelNF.pas' {FrmRelNF},
  UQRelNF in 'UQRelNF.pas' {FrmQRelNF},
  UQRelResNFAliq in 'UQRelResNFAliq.pas' {FrmQRelResNFAliq},
  USecaoGrupo in 'USecaoGrupo.pas' {FrmSecaoGrupo},
  UConsGrupo in 'UConsGrupo.pas' {FrmConsGrupo},
  UConsSubGrupo in 'UConsSubGrupo.pas' {FrmConsSubGrupo},
  UAlterarGRP in 'UAlterarGRP.pas' {FrmAlterarGRP},
  UAlterarSenha in 'UAlterarSenha.pas' {FrmAlterarSenha},
  URelVendasGrupoICMS in 'URelVendasGrupoICMS.pas' {FrmRelVendasGrupoICMS},
  UQRelVendasGrupoICMS in 'UQRelVendasGrupoICMS.pas' {FrmQRelVendasGrupoICMS},
  UQRelPrecosProgramados in 'UQRelPrecosProgramados.pas' {FrmQRelPrecosProgramados},
  UQRelEntradasGrupoICMS in 'UQRelEntradasGrupoICMS.pas' {FrmQRelEntradasGrupoICMS},
  URelBebidasFumo in 'URelBebidasFumo.pas' {FrmRelBebidasFumo},
  UQRelSemPisCofins in 'UQRelSemPisCofins.pas' {FrmQRelSemPisCofins},
  UQRelSemPisProduto in 'UQRelSemPisProduto.pas' {FrmQRelSemPisProduto},
  UIsentasPisEntradas in 'UIsentasPisEntradas.pas' {FrmIsentasPisEntradas},
  UQRelPisCofinsEntradasProduto in 'UQRelPisCofinsEntradasProduto.pas' {FrmQRelPisCofinsEntradasProduto},
  UQRelPisCofinsEntradasSecao in 'UQRelPisCofinsEntradasSecao.pas' {FrmQRelPisCofinsEntradasSecao},
  UFormacaoPreco in 'UFormacaoPreco.pas' {FrmFormacaoPreco},
  URelApuracaoICMS in 'URelApuracaoICMS.pas' {FrmRelApuracaoICMS},
  UQRelResInventarioPis in 'UQRelResInventarioPis.pas' {FrmQRelResInventarioPis},
  UQRelApuracaoICMS in 'UQRelApuracaoICMS.pas' {FrmQRelApuracao},
  UApuracaoPisCofins in 'UApuracaoPisCofins.pas' {FrmApuracaoPisCofins},
  UQRelApuracaoPisCofins in 'UQRelApuracaoPisCofins.pas' {FrmQRelApuracaoPisCofins},
  UQRelProdutosColetados in 'UQRelProdutosColetados.pas' {FrmQRelProdutosColetados},
  UAuxPromocao in 'UAuxPromocao.pas' {FrmAuxPromocao},
  UQRelPromocaoGeral in 'UQRelPromocaoGeral.pas' {FrmQRelPromocaoGeral},
  UCadVend in 'UCadVend.pas' {FrmCadVend},
  UConsVend in 'UConsVend.pas' {FrmConsVend},
  UQRelDuplicatasEntradas in 'UQRelDuplicatasEntradas.pas' {FrmQRelDuplicatasEntradas},
  URegistroProducao in 'URegistroProducao.pas' {FrmRegistroProducao},
  UConsRegistroProducao in 'UConsRegistroProducao.pas' {FrmConsRegistroProducao},
  UCadMarcas in 'UCadMarcas.pas' {FrmCadMarcas},
  UCadModelo in 'UCadModelo.pas' {FrmCadModelo},
  UConsMarcas in 'UConsMarcas.pas' {FrmConsMarcas},
  UConsModelos in 'UConsModelos.pas' {FrmConsModelos},
  UGerarRegSaidas in 'UGerarRegSaidas.pas' {FrmGerarRegSaidas},
  UCadUnidadeMedida in 'UCadUnidadeMedida.pas' {FrmCadUnidadeMedida},
  UConsUnidadeMedida in 'UConsUnidadeMedida.pas' {FrmConsUnidadeMedida},
  UConsPreVenda in 'UConsPreVenda.pas' {FrmConsPreVenda},
  UConsOrcamento in 'UConsOrcamento.pas' {FrmConsOrcamento},
  UConsOrdemServico in 'UConsOrdemServico.pas' {FrmConsOrdemServico},
  UQRelOrcamentosEmitidos in 'UQRelOrcamentosEmitidos.pas' {FrmQRelOrcamentosEmitidos},
  UQRelPreVendasEmitidas in 'UQRelPreVendasEmitidas.pas' {FrmQRelPreVendaEmitidas},
  UQRelOSEmitidas in 'UQRelOSEmitidas.pas' {FrmQRelOsEmitidas},
  UCadFormasPagamentos in 'UCadFormasPagamentos.pas' {FrmCadFormaPagamento},
  UConsFormasPagamento in 'UConsFormasPagamento.pas' {FrmConsFormasPagamento},
  UCadCentroCusto in 'UCadCentroCusto.pas' {FrmCadCentroCusto},
  UConsCentroCusto in 'UConsCentroCusto.pas' {FrmConsCentroCusto},
  UDuplicataADM in 'UDuplicataADM.pas' {FrmDuplicataADM},
  UDadosAdm in 'UDadosAdm.pas' {FrmDadosAdm},
  UAlteraParcelaCTR in 'UAlteraParcelaCTR.pas' {FrmAlteraParcelaADM},
  URelContasReceberCartao in 'URelContasReceberCartao.pas' {FrmRelContasReceberCartao},
  UCadClassifContasReceber in 'UCadClassifContasReceber.pas' {FrmCadClassifContasReceber},
  UConsClassifContasReceber in 'UConsClassifContasReceber.pas' {FrmConsClassifContasReceber},
  UQRelCTRAdm in 'UQRelCTRAdm.pas' {FrmQRelCTRAdm},
  UCadLocaisEstoque in 'UCadLocaisEstoque.pas' {FrmCadLocaisEstoque},
  UConsLocaisEstoque in 'UConsLocaisEstoque.pas' {FrmConsLocaisEstoque},
  UCadSetorEstoque in 'UCadSetorEstoque.pas' {FrmCadSetorEstoque},
  UConsSetorEstoque in 'UConsSetorEstoque.pas' {FrmConsSetorEstoque},
  UTransfLocaisEstoque in 'UTransfLocaisEstoque.pas' {FrmTransfLocaisEstoque},
  UConsVendas in 'UConsVendas.pas' {FrmConsVendas},
  UConsBandeiraCartao in 'UConsBandeiraCartao.pas' {FrmConsBandeiraCartao},
  UDadosNotaFiscal in 'UDadosNotaFiscal.pas' {FrmDadosNotaFiscal},
  UFrmStatusNfe in 'UFrmStatusNfe.pas' {FrmStatusNfe},
  UConsMunicipios in 'UConsMunicipios.pas' {FrmConsMunicipios},
  UGeraRegSaidasMapaResumo in 'UGeraRegSaidasMapaResumo.pas' {FrmGerarRegSaidasMapaResumo},
  UMMA_OS in 'UMMA_OS.pas' {FrmMMA_OS},
  UDeletaOS in 'UDeletaOS.pas' {frmDeletaOS},
  UMMA_ITENS in 'UMMA_ITENS.pas' {frmMMA_ITENS},
  UMMA_Fechamento in 'UMMA_Fechamento.pas' {frmMMA_Fechamento},
  UMMA_TROCO in 'UMMA_TROCO.pas' {frmMMA_TROCO},
  UMMAREL_OS_ABERTURA in 'UMMAREL_OS_ABERTURA.pas' {frmMMAREL_OS_ABERTURA},
  UMMA_REL_FECHAMENTO in 'UMMA_REL_FECHAMENTO.pas' {frmREL_FECHAMENTO},
  frmMMA_Config in 'frmMMA_Config.pas' {frmMMA_ConfigT},
  UPopUp in 'UPopUp.pas' {Popup},
  URel_FechaVenda in 'URel_FechaVenda.pas' {frmRel_Fechavenda},
  UEstoqueConsignado in 'UEstoqueConsignado.pas' {frmEstoqueConsignado},
  UResumoConsignado in 'UResumoConsignado.pas' {frmResumoConsignado},
  UKRelEtiquetas in 'UKRelEtiquetas.pas' {frmKRelEtiquetas},
  UMensagens in 'UMensagens.pas' {frmMensagens},
  USpedPis in 'USpedPis.pas' {frmSpedPis},
  Func in 'UnitsImport\Func.pas',
  UAssocia in 'UnitsImport\UAssocia.pas' {frmAssocia},
  UFrameComXML in 'UnitsImport\UFrameComXML.pas' {TFrameComXML: TFrame},
  UImportXML in 'UnitsImport\UImportXML.pas' {ImportXML},
  UPrincipal in 'UnitsImport\UPrincipal.pas' {PrincipalXML},
  UConsVendasCF in 'UConsVendasCF.pas' {FrmConsVendasCF},
  UTRelProdutoCliente in 'UTRelProdutoCliente.pas' {frmRelProdutoCliente},
  UselIntervaloProduto in 'UselIntervaloProduto.pas' {SelIntervaloProduto},
  UCartaCorrecao in 'UCartaCorrecao.pas' {frmCadCartaCorrecao},
  UDMI in 'UDMI.pas' {DMI: TDataModule},
  UDMefd in 'UDMefd.pas' {DMefd: TDataModule},
  UCadTabPreco in 'UCadTabPreco.pas' {FrmCadTabPreco},
  UConfigurarPisCofins in 'UConfigurarPisCofins.pas' {frmConfigurarPisCofins},
  UDialog in 'UDialog.pas' {frmDialog},
  UCadSacadoBoleto in 'UCadSacadoBoleto.pas' {frmCadSacadoBoleto},
  UConsSacado in 'UConsSacado.pas' {frmConsSacado},
  UGerenciaRemessas in 'UGerenciaRemessas.pas' {frmGerenciaRemessas},
  UCadRemessa in 'UCadRemessa.pas' {frmCadRemessa},
  UImportaRetorno in 'UImportaRetorno.pas' {frmImportaRetorno},
  UComissoesVendedores in 'UComissoesVendedores.pas' {frmComissoesVendedores},
  UfrmManifestacao in 'UfrmManifestacao.pas' {frmManifestacao},
  UdmEFDFiscal in 'UdmEFDFiscal.pas' {dmEFDFiscal: TDataModule},
  UfrmSpedFiscal in 'UfrmSpedFiscal.pas' {frmSpedFiscal},
  UCFOP_Tributacoes in 'UCFOP_Tributacoes.pas' {frmCFOP_Tributacoes},
  USelecionaCFOPS in 'USelecionaCFOPS.pas' {frmSelecionaCFOPS},
  UCadComissosXDescontos in 'UCadComissosXDescontos.pas' {frmCadComissosXDescontos},
  URelComissoes in 'URelComissoes.pas' {frmRelComissoes},
  cep in 'cep.pas',
  UAtualizaIBPT in 'UAtualizaIBPT.pas' {frmAtualizaIBPT},
  UCidadesVendedor in 'UCidadesVendedor.pas' {frmCidades_Vendedor},
  UConsRegiao in 'UConsRegiao.pas' {frmConsRegiao},
  UCadRegiao in 'UCadRegiao.pas' {frmCadRegiao},
  USincronizaManifestacao in 'USincronizaManifestacao.pas',
  uBuscaXml in 'RecuperarXML\uBuscaXml.pas' {frmBuscarXML},
  ACBrHTMLtoXML in 'RecuperarXML\ACBrHTMLtoXML.pas',
  UsemXML in 'UsemXML.pas' {FrameSemXML: TFrame},
  UConfigPostos in 'UConfigPostos.pas' {frmConfigPostos},
  UNovoFormulario in 'UNovoFormulario.pas',
  UNovosComponentes in 'UNovosComponentes.pas',
  UCadTeclasAtalho in 'UCadTeclasAtalho.pas' {frmCadTeclasAtalho},
  UConsTeclasAtalho in 'UConsTeclasAtalho.pas' {frmConsTeclasAtalho},
  frmConsultaCPFCNPJ in 'frmConsultaCPFCNPJ.pas' {fmConsultaReceita},
  UNovoPrincipal in 'UNovoPrincipal.pas' {frmMenu},
  UformResumos in 'UformResumos.pas' {frmResumos},
  UGerenciamentoNFe in 'SLNFe\UGerenciamentoNFe.pas' {FrmGerenciamentoNFe},
  UImprimeNotaFiscal in 'SLNFe\UImprimeNotaFiscal.pas',
  UNotaFiscal in 'SLNFe\UNotaFiscal.pas' {FrmNotaFiscal},
  USendemail in 'SLNFe\USendemail.pas' {FrmSendEmail},
  Ubibli2 in 'UNITS\Ubibli2.pas',
  UDicImp in 'Dicionario\Impressoras\UDicImp.pas',
  UDicImpForm in 'Dicionario\Impressoras\UDicImpForm.pas' {frmKadoshiSelPrinter},
  UDicLib in 'Dicionario\UDicLib.pas',
  URelGerais in 'Dicionario\URelGerais.pas' {dmRelGerais: TDataModule},
  UfechaVendaParcelas in 'UfechaVendaParcelas.pas' {frmFechaVendaParcelas},
  UDownloadFile in 'TarefasSegundoPlano\UDownloadFile.pas',
  UTarefasSP in 'TarefasSegundoPlano\UTarefasSP.pas',
  UTSP in 'TarefasSegundoPlano\UTSP.pas' {frmTSP: TFrame},
  UEstatisticas in 'UEstatisticas.pas' {frmEstatisticas: TFrame},
  UConsNCM in 'UConsNCM.pas' {frmConsNCM},
  UDicTributacao in 'Dicionario\Tributacoes\UDicTributacao.pas',
  UCadNovoDB in 'UNITS\UCadNovoDB.pas' {frmCadNovoDB},
  UTributacaoPerfil in 'UTributacaoPerfil.pas' {frmCadTributacaoPerfil},
  UCadICMS in 'UCadICMS.pas' {frmCadICMS},
  UCadProduto in 'UCadProduto.pas' {FrmCadProduto},
  UCadEtiquetasModelos in 'UCadEtiquetasModelos.pas' {frmCadEtiquetasModelos},
  UConfigEtiquetas in 'UConfigEtiquetas.pas' {frmConfigEtiquetas},
  UCadNewCaixa in 'UCadNewCaixa.pas' {frmCadNewCaixa},
  UNewCaixaGrupos in 'UNewCaixaGrupos.pas' {frmNewCaixaGrupos},
  UBuscaPlano in 'UBuscaPlano.pas' {frmBuscaPlano},
  UDicFluxo in 'Dicionario\FluxoCaixa\UDicFluxo.pas',
  UAbreCaixa in 'Dicionario\FluxoCaixa\UAbreCaixa.pas' {frmAbreCaixa},
  UNewCaixaMovimentos in 'Dicionario\FluxoCaixa\UNewCaixaMovimentos.pas' {frmNewCaixaMovimentos},
  UFechaCaixa in 'UFechaCaixa.pas' {frmFechaCaixa},
  UCadNewFormas in 'UCadNewFormas.pas' {frmCadNewFormas},
  UdmRelatorios in 'UdmRelatorios.pas' {dmRelatorios: TDataModule},
  UConsCest in 'UConsCest.pas' {frmConsCEST},
  ws_trib in 'ws_trib.pas',
  UWebServiceTributacoes in 'UWebServiceTributacoes.pas',
  URelFluxoNew in 'URelFluxoNew.pas' {frmRelFluxonew},
  URelPagas in 'URelPagas.pas' {FrmRelPagas},
  UOS in 'UOS.pas' {frmCadOS},
  UFechamentoOrdemServico in 'UFechamentoOrdemServico.pas' {frmFechamentoOS},
  URelOS in 'URelOS.pas' {frmRelOS},
  UCadNotaFiscalServico in 'UCadNotaFiscalServico.pas' {frmCadNotaFiscalServico},
  UGerenciamentoNFSE in 'UGerenciamentoNFSE.pas' {frmGerenciamentoNFSE},
  UCadSNGPC in 'UCadSNGPC.pas' {frmCadSNGPC},
  UGerarXMLSNGPC in 'UGerarXMLSNGPC.pas' {FrmGerarXMLSNGPC},
  UCadSNGPCEntrada in 'UCadSNGPCEntrada.pas' {frmCadSNGPCEntrada},
  UCadPreVenda in 'UCadPreVenda.pas' {frmCadPreVenda},
  UCadTrocas in 'UCadTrocas.pas' {frmCadTrocas},
  URelProducao in 'URelProducao.pas' {FrmRelProducao};

{$R *.res}


begin
  Application.Initialize;
  Application.Title := 'Caiman Gestão Empresarial';
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TfrmDeletaOS, frmDeletaOS);
  Application.CreateForm(TDMI, DMI);
  Application.CreateForm(TDMefd, DMefd);
  Application.CreateForm(TdmEFDFiscal, dmEFDFiscal);
  Application.CreateForm(TdmRelGerais, dmRelGerais);
  Application.CreateForm(TdmRelatorios, dmRelatorios);
  Application.CreateForm(TFrmRelPagas, FrmRelPagas);
  Application.Run;
end.

